version: '3'

services:
  app:
    build: .
    container_name: todo_app
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'

  db:
    image: bitnami/postgresql:latest
    container_name: postgresql
    restart: always
    ports:
      - 5445:5432
    volumes:
      - postgresql_data:/bitnami/postgresql
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres123
      POSTGRESQL_DATABASE: todo-app

volumes:
  postgresql_data:
    driver: local

networks:
  my-network:
    external: true
